title: docs.md

icons:
  favicon: /images/favicon.png
  header: /images/logo.svg

code_highlight_theme: one-dark-pro

navigation:
  - title: Getting started
    items:
      - title: Introduction
        url: /
      - title: Elements
        url: /elements.html
      - title: Changelog
        url: /changelog.html
      - title: Roadmap
        url: /roadmap.html
  - title: Configuration
    items:
      - title: Config file
        url: /configuration/config.html
        items:
          - title: Navigation
            url: /configuration/config/navigation.html
      - title: Styling
        url: /configuration/styling.html
  - title: Custom elements
    items:
      - title: Aside
        url: /elements/aside.html
      - title: Parameters
        url: /elements/parameters.html
      - title: Code samples
        url: /elements/code-samples.html
