name: Build and Push Docker Image

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - dev-kirick

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Prepare Docker Multibuilder
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from package.json
        id: package_version
        run: |
          sudo apt-get update \
          && sudo apt-get install -y jq \
          && echo "PACKAGE_VERSION=$(jq -r .version source/package.json)" >> $GITHUB_ENV

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "kirickme/docs.md:${{ env.PACKAGE_VERSION }}"
